Salvatore1985/boolBnB

app/Http/Controllers/User/ApartmentsController.php
public/js/app.js
resources/views/User/Apartments/index.blade.php

completed CRUD index

---

app/Http/Controllers/User/ApartmentsController.php
resources/views/User/Apartments/show.blade.php

added delete CRUD to apartments

create show for single apartment

---

app/Http/Controllers/User/ApartmentsController.php
resources/views/User/Apartments/edit.blade.php

Edit CRUD of an apartment

---

resources/views/User/Apartments/show.blade.php

add map show

---

app/Http/Controllers/Api/ApartmentController.php
routes/api.php

add function search with laravel

add function search

---

app/Http/Controllers/User/ApartmentsController.php
resources/views/User/Apartments/create.blade.php
resources/views/User/Apartments/edit.blade.php

validation create and edit complete in italian

Create edit validation

---

app/Http/Controllers/Auth/LoginController.php
app/Http/Controllers/Auth/RegisterController.php
database/migrations/2014_10_12_000000_create_users_table.php
database/seeds/UserSeeder.php
resources/lang/en/auth.php
resources/lang/en/passwords.php
resources/views/User/Apartments/create.blade.php
resources/views/auth/login.blade.php
resources/views/auth/register.blade.php

Validation login

---

resources/js/view/App.vue
resources/sass/_create_style.scss
resources/sass/app.scss
resources/views/User/Apartments/index.blade.php
resources/views/User/home.blade.php
resources/views/guests/home.blade.php
resources/views/layouts/app.blade.php
resources/views/layouts/createPage.blade.php
resources/views/layouts/editPage.blade.php
routes/web.php

Header links

---

public/css/app.css
public/js/front.js
public/js/user.js
resources/sass/_create_style.scss
resources/sass/app.scss
resources/views/User/Apartments/create.blade.php
resources/views/layouts/app.blade.php
resources/views/layouts/createPage.blade.php

add style form create

---

resources/views/User/Apartments/create.blade.php

update create input address with tomtom api

---

resources/views/User/Apartments/edit.blade.php

completed edit CRUD with TomTom

Add tomtom edit crud

---

app/Http/Controllers/User/ApartmentsController.php
app/Http/Controllers/User/ImagesController.php
public/js/front.js
resources/views/User/Apartments/edit.blade.php
routes/web.php

added and removing images from CRUD apartment

Edit images

---

database/seeds/ServiceSeeder.php

change the names of services to italian

feat. changed names in services to italian

---

app/Http/Controllers/User/ApartmentsController.php
resources/views/User/Apartments/show.blade.php

feat. added services to CRUD show apartment

feat. added services to CRUD show apartment

---

app/Http/Controllers/User/ApartmentsController.php
database/seeds/ServiceSeeder.php
public/js/front.js
resources/js/components/Apartment.vue
resources/js/components/Header.vue
resources/views/User/Apartments/edit.blade.php
resources/views/User/Apartments/index.blade.php
resources/views/User/Apartments/show.blade.php

debugged services in edit, create and show

Debug services

---

public/js/front.js
resources/js/components/Apartment.vue

debugged images in Vue

---

app/Http/Controllers/Auth/RegisterController.php
database/migrations/2014_10_12_000000_create_users_table.php
database/seeds/UserSeeder.php
public/js/user.js
resources/lang/en/validation.php
resources/views/User/Apartments/index.blade.php
resources/views/auth/register.blade.php
resources/views/layouts/app.blade.php

add validation register

---

app/Http/Controllers/User/ApartmentsController.php
resources/views/User/Apartments/create.blade.php
resources/views/User/Apartments/edit.blade.php
resources/views/User/Apartments/index.blade.php
resources/views/auth/login.blade.php
resources/views/auth/register.blade.php

added feature and client side validations

Adding features

---

app/Http/Controllers/User/ApartmentsController.php

added function Auth apartment id

feat. added auth condition

---

resources/views/User/Apartments/index.blade.php

add modify style card apartment index

---

app/Http/Controllers/Api/ApartmentController.php
public/js/front.js
public/js/user.js
resources/js/Pages/Apartments.vue
resources/js/Pages/SingleApartment.vue
resources/js/components/Apartment.vue
resources/js/components/Header.vue
resources/js/components/Main.vue
resources/js/front.js

added apartment show and debug API call

feat. singleApartment and user name added to Apartment users info

---

public/js/front.js
resources/js/Pages/SingleApartment.vue
resources/js/front.js

beginning of style single Apartment

---

public/css/app.css
public/js/front.js
public/js/user.js
resources/js/Pages/SingleApartment.vue
resources/sass/_create_style.scss

da continuare Thom

---

resources/js/Pages/Apartments.vue
resources/js/components/Pagination.vue

update pagination vue

---

resources/views/User/home.blade.php

da fixare il layout

---

resources/sass/_create_style.scss
resources/views/User/Apartments/index.blade.php
resources/views/User/Apartments/show.blade.php
resources/views/layouts/partials/header.blade.php

navbaradd publicato cars and home

---

resources/js/Pages/SingleApartment.vue
resources/js/components/Carousel.vue
resources/js/components/TomTomMap.vue
resources/sass/_create_style.scss
resources/views/layouts/partials/header.blade.php

add style page info apartment

---

resources/js/components/Footer.vue
resources/sass/_create_style.scss
resources/sass/_variables.scss

add footer

---

resources/js/Pages/Apartments.vue

Vue js tomtom input

---

app/Http/Controllers/User/ApartmentsController.php
public/css/app.css
resources/views/User/home.blade.php

Adding show messages

---

resources/views/User/Apartments/show.blade.php

style button
